In [2]:
import pandas as pd
import matplotlib.pyplot as plt

DATA_DIR = "data"
# step 1 : loading the data
sales = pd.read_csv(f"{DATA_DIR}/sales.csv")
inventory = pd.read_csv(f"{DATA_DIR}/inventory.csv")
finance = pd.read_csv(f"{DATA_DIR}/finance.csv")
vendors = pd.read_csv(f"{DATA_DIR}/vendors.csv")


# basic stats 
print("sales:    ", sales.shape)
print("inventory:", inventory.shape)
print("finance:  ", finance.shape)
print("vendors:  ", vendors.shape)

sales:     (9157, 9)
inventory: (100, 8)
finance:   (5000, 6)
vendors:   (20, 13)

In [3]:
sales.head()

,date,sku,qty,revenue,region,temperature,rainfall,humidity,weather_condition
0,2022-10-03,SKU060,1,3953.37,North,16.7,40.9,67.0,Rainy
1,2020-06-22,SKU058,9,18397.09,South,24.4,57.4,82.0,Rainy
2,2020-05-27,SKU086,5,88407.28,North,20.2,352.8,75.9,Thunderstorm
3,2021-04-27,SKU044,9,235192.77,West,20.6,64.6,66.5,Rainy
4,2020-04-01,SKU081,14,3525.75,North,44.1,1.2,30.6,Sunny

In [4]:
inventory.head(2)

,sku,name,category,region,qty,reorder_threshold,unit_cost,vendor_id
0,SKU001,Mixer Grinder,Kitchen Appliances,North,41,16,3500,V001
1,SKU002,Pressure Cooker,Kitchen Appliances,North,55,30,2500,V018

In [5]:
# merge the columns from inventory ( category, name, region as home_region)
inventory.rename(columns={'region': 'home_region'}, inplace=True)
df = pd.merge(sales, inventory[['sku', 'category', 'name', 'home_region']], on='sku', how='left')

df.head(2)

,date,sku,qty,revenue,region,temperature,rainfall,humidity,weather_condition,category,name,home_region
0,2022-10-03,SKU060,1,3953.37,North,16.7,40.9,67.0,Rainy,Personal Care,Epilator,South
1,2020-06-22,SKU058,9,18397.09,South,24.4,57.4,82.0,Rainy,Personal Care,Hair Trimmer,Central

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9157 entries, 0 to 9156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               9157 non-null   object
 1   sku                9157 non-null   object
 2   qty                9157 non-null   int64
 3   revenue            9157 non-null   float64
 4   region             9157 non-null   object
 5   temperature        9157 non-null   object
 6   rainfall           9157 non-null   float64
 7   humidity           9157 non-null   float64
 8   weather_condition  9157 non-null   object
 9   category           9157 non-null   object
 10  name               9157 non-null   object
 11  home_region        9157 non-null   object
dtypes: float64(3), int64(1), object(8)
memory usage: 858.6+ KB

In [7]:
before = len(df)
df["temperature"] = pd.to_numeric(df["temperature"], errors="coerce")
n_bad = df["temperature"].isna().sum()
print(f"{n_bad} row(s) with non-numeric temperature -> dropping")
df = df.dropna(subset=["temperature"]).reset_index(drop=True)

1 row(s) with non-numeric temperature -> dropping

In [8]:
df["date"] = pd.to_datetime(df["date"])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9156 entries, 0 to 9155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               9156 non-null   datetime64[ns]
 1   sku                9156 non-null   object
 2   qty                9156 non-null   int64
 3   revenue            9156 non-null   float64
 4   region             9156 non-null   object
 5   temperature        9156 non-null   float64
 6   rainfall           9156 non-null   float64
 7   humidity           9156 non-null   float64
 8   weather_condition  9156 non-null   object
 9   category           9156 non-null   object
 10  name               9156 non-null   object
 11  home_region        9156 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 858.5+ KB

In [10]:
# feature engineering 
df["month"] = df["date"].dt.month
df["day_of_week"] = df["date"].dt.dayofweek
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [11]:
df.head(2)

,date,sku,qty,revenue,region,temperature,rainfall,humidity,weather_condition,category,name,home_region,month,day_of_week,is_weekend
0,2022-10-03,SKU060,1,3953.37,North,16.7,40.9,67.0,Rainy,Personal Care,Epilator,South,10,0,0
1,2020-06-22,SKU058,9,18397.09,South,24.4,57.4,82.0,Rainy,Personal Care,Hair Trimmer,Central,6,0,0

In [13]:
df["day_of_week"].value_counts()

day_of_week
2    1326
1    1325
5    1306
0    1305
3    1305
4    1304
6    1285
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

encoders = {}
for col in ["sku", "category", "region", "weather_condition"]:
    le = LabelEncoder()
    df[col + "_enc"] = le.fit_transform(df[col])
    encoders[col] = le

In [15]:
feature_cols = [
    "sku_enc", "category_enc", "region_enc", "weather_condition_enc",
    "temperature", "rainfall", "humidity",
    "month", "day_of_week", "is_weekend",
]

target_col = "qty"

X = df[feature_cols]
y = df[target_col]

In [16]:
df_sorted = df.sort_values("date").reset_index(drop=True)

In [17]:
# step 3 : split the data into 2 category --> time based spliting
split_idx = int(len(df_sorted) * 0.85)
split_date = df_sorted.loc[split_idx, "date"]

train_df = df_sorted[df_sorted["date"] < split_date]
test_df = df_sorted[df_sorted["date"] >= split_date]

In [18]:
train_df.shape,test_df.shape

((7778, 19), (1378, 19))

In [20]:
X_train, y_train = train_df[feature_cols], train_df[target_col]
X_test, y_test = test_df[feature_cols], test_df[target_col]

In [21]:
pip install xgboost

Collecting xgboost
  Using cached xgboost-3.4.1-py3-none-macosx_12_0_arm64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/ai_engineering_19th_may/ai-env/lib/python3.13/site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/ai_engineering_19th_may/ai-env/lib/python3.13/site-packages (from xgboost) (1.18.0)
Using cached xgboost-3.4.1-py3-none-macosx_12_0_arm64.whl (2.4 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1

[notice] A new release of pip is available: 25.3 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [22]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error
import pickle

In [23]:
model = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

In [24]:
model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=True,
)

[0]	validation_0-rmse:4.85638
[1]	validation_0-rmse:4.84684
[2]	validation_0-rmse:4.84168
[3]	validation_0-rmse:4.83068
[4]	validation_0-rmse:4.82484
[5]	validation_0-rmse:4.81936
[6]	validation_0-rmse:4.81571
[7]	validation_0-rmse:4.81008
[8]	validation_0-rmse:4.80198
[9]	validation_0-rmse:4.79758
[10]	validation_0-rmse:4.79215
[11]	validation_0-rmse:4.78933
[12]	validation_0-rmse:4.78472
[13]	validation_0-rmse:4.78130
[14]	validation_0-rmse:4.78050
[15]	validation_0-rmse:4.77683
[16]	validation_0-rmse:4.77306
[17]	validation_0-rmse:4.77074
[18]	validation_0-rmse:4.76806
[19]	validation_0-rmse:4.76751
[20]	validation_0-rmse:4.76086
[21]	validation_0-rmse:4.75770
[22]	validation_0-rmse:4.75890
[23]	validation_0-rmse:4.75820
[24]	validation_0-rmse:4.75652
[25]	validation_0-rmse:4.75423
[26]	validation_0-rmse:4.75450
[27]	validation_0-rmse:4.75388
[28]	validation_0-rmse:4.75256
[29]	validation_0-rmse:4.75140
[30]	validation_0-rmse:4.75322
[31]	validation_0-rmse:4.75060
[32]	validation_0-rmse:4.74985
[33]	validation_0-rmse:4.75121
[34]	validation_0-rmse:4.75101
[35]	validation_0-rmse:4.75373
[36]	validation_0-rmse:4.75567
[37]	validation_0-rmse:4.75607
[38]	validation_0-rmse:4.75655
[39]	validation_0-rmse:4.75563
[40]	validation_0-rmse:4.75776
[41]	validation_0-rmse:4.75843
[42]	validation_0-rmse:4.76048
[43]	validation_0-rmse:4.75768
[44]	validation_0-rmse:4.75681
[45]	validation_0-rmse:4.75648
[46]	validation_0-rmse:4.75448
[47]	validation_0-rmse:4.75422
[48]	validation_0-rmse:4.75421
[49]	validation_0-rmse:4.75372
[50]	validation_0-rmse:4.75403
[51]	validation_0-rmse:4.75434
[52]	validation_0-rmse:4.75547
[53]	validation_0-rmse:4.75518
[54]	validation_0-rmse:4.75654
[55]	validation_0-rmse:4.75647
[56]	validation_0-rmse:4.75631
[57]	validation_0-rmse:4.75862
[58]	validation_0-rmse:4.75792
[59]	validation_0-rmse:4.75806
[60]	validation_0-rmse:4.75698
[61]	validation_0-rmse:4.75711
[62]	validation_0-rmse:4.75683
[63]	validation_0-rmse:4.75679
[64]	validation_0-rmse:4.75648
[65]	validation_0-rmse:4.75533
[66]	validation_0-rmse:4.75436
[67]	validation_0-rmse:4.75427
[68]	validation_0-rmse:4.75551
[69]	validation_0-rmse:4.75634
[70]	validation_0-rmse:4.75608
[71]	validation_0-rmse:4.75651
[72]	validation_0-rmse:4.75673
[73]	validation_0-rmse:4.75665
[74]	validation_0-rmse:4.75632
[75]	validation_0-rmse:4.75706
[76]	validation_0-rmse:4.75686
[77]	validation_0-rmse:4.75591
[78]	validation_0-rmse:4.75622
[79]	validation_0-rmse:4.75678
[80]	validation_0-rmse:4.75784
[81]	validation_0-rmse:4.75980
[82]	validation_0-rmse:4.76011
[83]	validation_0-rmse:4.76044
[84]	validation_0-rmse:4.76074
[85]	validation_0-rmse:4.75935
[86]	validation_0-rmse:4.76028
[87]	validation_0-rmse:4.75992
[88]	validation_0-rmse:4.76041
[89]	validation_0-rmse:4.76028
[90]	validation_0-rmse:4.76144
[91]	validation_0-rmse:4.76016
[92]	validation_0-rmse:4.75951
[93]	validation_0-rmse:4.75992
[94]	validation_0-rmse:4.76038
[95]	validation_0-rmse:4.76081
[96]	validation_0-rmse:4.76139
[97]	validation_0-rmse:4.76103
[98]	validation_0-rmse:4.76102
[99]	validation_0-rmse:4.75980
[100]	validation_0-rmse:4.75955
[101]	validation_0-rmse:4.75942
[102]	validation_0-rmse:4.76026
[103]	validation_0-rmse:4.75888
[104]	validation_0-rmse:4.75809
[105]	validation_0-rmse:4.75808
[106]	validation_0-rmse:4.75763
[107]	validation_0-rmse:4.75836
[108]	validation_0-rmse:4.75889
[109]	validation_0-rmse:4.75826
[110]	validation_0-rmse:4.75869
[111]	validation_0-rmse:4.75828
[112]	validation_0-rmse:4.75833
[113]	validation_0-rmse:4.75824
[114]	validation_0-rmse:4.75829
[115]	validation_0-rmse:4.75781
[116]	validation_0-rmse:4.75886
[117]	validation_0-rmse:4.75861
[118]	validation_0-rmse:4.75731
[119]	validation_0-rmse:4.76064
[120]	validation_0-rmse:4.76026
[121]	validation_0-rmse:4.76018
[122]	validation_0-rmse:4.76202
[123]	validation_0-rmse:4.76263
[124]	validation_0-rmse:4.76203
[125]	validation_0-rmse:4.76263
[126]	validation_0-rmse:4.76404
[127]	validation_0-rmse:4.76337
[128]	validation_0-rmse:4.76369
[129]	validation_0-rmse:4.76416
[130]	validation_0-rmse:4.76332
[131]	validation_0-rmse:4.76433
[132]	validation_0-rmse:4.76497
[133]	validation_0-rmse:4.76446
[134]	validation_0-rmse:4.76563
[135]	validation_0-rmse:4.76630
[136]	validation_0-rmse:4.76617
[137]	validation_0-rmse:4.76699
[138]	validation_0-rmse:4.76782
[139]	validation_0-rmse:4.76915
[140]	validation_0-rmse:4.76939
[141]	validation_0-rmse:4.76999
[142]	validation_0-rmse:4.76927
[143]	validation_0-rmse:4.76934
[144]	validation_0-rmse:4.76976
[145]	validation_0-rmse:4.76853
[146]	validation_0-rmse:4.76951
[147]	validation_0-rmse:4.77006
[148]	validation_0-rmse:4.77054
[149]	validation_0-rmse:4.77069
[150]	validation_0-rmse:4.77023
[151]	validation_0-rmse:4.76985
[152]	validation_0-rmse:4.76975
[153]	validation_0-rmse:4.77182
[154]	validation_0-rmse:4.77394
[155]	validation_0-rmse:4.77329
[156]	validation_0-rmse:4.77367
[157]	validation_0-rmse:4.77541
[158]	validation_0-rmse:4.77543
[159]	validation_0-rmse:4.77577
[160]	validation_0-rmse:4.77540
[161]	validation_0-rmse:4.77514
[162]	validation_0-rmse:4.77514
[163]	validation_0-rmse:4.77585
[164]	validation_0-rmse:4.77588
[165]	validation_0-rmse:4.77461
[166]	validation_0-rmse:4.77661
[167]	validation_0-rmse:4.77724
[168]	validation_0-rmse:4.77770
[169]	validation_0-rmse:4.77759
[170]	validation_0-rmse:4.77923
[171]	validation_0-rmse:4.78113
[172]	validation_0-rmse:4.78229
[173]	validation_0-rmse:4.78423
[174]	validation_0-rmse:4.78455
[175]	validation_0-rmse:4.78444
[176]	validation_0-rmse:4.78648
[177]	validation_0-rmse:4.78517
[178]	validation_0-rmse:4.78468
[179]	validation_0-rmse:4.78520
[180]	validation_0-rmse:4.78544
[181]	validation_0-rmse:4.78547
[182]	validation_0-rmse:4.78567
[183]	validation_0-rmse:4.78575
[184]	validation_0-rmse:4.78387
[185]	validation_0-rmse:4.78500
[186]	validation_0-rmse:4.78564
[187]	validation_0-rmse:4.78695
[188]	validation_0-rmse:4.78730
[189]	validation_0-rmse:4.78800
[190]	validation_0-rmse:4.78878
[191]	validation_0-rmse:4.79054
[192]	validation_0-rmse:4.79147
[193]	validation_0-rmse:4.79285
[194]	validation_0-rmse:4.79393
[195]	validation_0-rmse:4.79602
[196]	validation_0-rmse:4.79486
[197]	validation_0-rmse:4.79480
[198]	validation_0-rmse:4.79536
[199]	validation_0-rmse:4.79485
[200]	validation_0-rmse:4.79554
[201]	validation_0-rmse:4.79552
[202]	validation_0-rmse:4.79636
[203]	validation_0-rmse:4.79676
[204]	validation_0-rmse:4.79721
[205]	validation_0-rmse:4.79722
[206]	validation_0-rmse:4.79788
[207]	validation_0-rmse:4.79992
[208]	validation_0-rmse:4.79955
[209]	validation_0-rmse:4.80003
[210]	validation_0-rmse:4.80065
[211]	validation_0-rmse:4.80023
[212]	validation_0-rmse:4.80130
[213]	validation_0-rmse:4.80079
[214]	validation_0-rmse:4.80088
[215]	validation_0-rmse:4.80164
[216]	validation_0-rmse:4.80048
[217]	validation_0-rmse:4.79962
[218]	validation_0-rmse:4.79872
[219]	validation_0-rmse:4.79876
[220]	validation_0-rmse:4.79921
[221]	validation_0-rmse:4.80008
[222]	validation_0-rmse:4.79996
[223]	validation_0-rmse:4.80029
[224]	validation_0-rmse:4.80012
[225]	validation_0-rmse:4.80028
[226]	validation_0-rmse:4.80058
[227]	validation_0-rmse:4.80122
[228]	validation_0-rmse:4.80169
[229]	validation_0-rmse:4.80215
[230]	validation_0-rmse:4.80389
[231]	validation_0-rmse:4.80479
[232]	validation_0-rmse:4.80497
[233]	validation_0-rmse:4.80480
[234]	validation_0-rmse:4.80580
[235]	validation_0-rmse:4.80590
[236]	validation_0-rmse:4.80409
[237]	validation_0-rmse:4.80438
[238]	validation_0-rmse:4.80471
[239]	validation_0-rmse:4.80502
[240]	validation_0-rmse:4.80575
[241]	validation_0-rmse:4.80601
[242]	validation_0-rmse:4.80622
[243]	validation_0-rmse:4.80614
[244]	validation_0-rmse:4.80734
[245]	validation_0-rmse:4.80747
[246]	validation_0-rmse:4.80838
[247]	validation_0-rmse:4.80902
[248]	validation_0-rmse:4.80944
[249]	validation_0-rmse:4.80922
[250]	validation_0-rmse:4.80862
[251]	validation_0-rmse:4.80920
[252]	validation_0-rmse:4.80881
[253]	validation_0-rmse:4.80932
[254]	validation_0-rmse:4.81041
[255]	validation_0-rmse:4.81079
[256]	validation_0-rmse:4.81025
[257]	validation_0-rmse:4.81022
[258]	validation_0-rmse:4.81167
[259]	validation_0-rmse:4.81196
[260]	validation_0-rmse:4.81163
[261]	validation_0-rmse:4.81296
[262]	validation_0-rmse:4.81415
[263]	validation_0-rmse:4.81392
[264]	validation_0-rmse:4.81258
[265]	validation_0-rmse:4.81317
[266]	validation_0-rmse:4.81394
[267]	validation_0-rmse:4.81426
[268]	validation_0-rmse:4.81352
[269]	validation_0-rmse:4.81480
[270]	validation_0-rmse:4.81477
[271]	validation_0-rmse:4.81528
[272]	validation_0-rmse:4.81508
[273]	validation_0-rmse:4.81445
[274]	validation_0-rmse:4.81581
[275]	validation_0-rmse:4.81673
[276]	validation_0-rmse:4.81588
[277]	validation_0-rmse:4.81735
[278]	validation_0-rmse:4.81732
[279]	validation_0-rmse:4.81716
[280]	validation_0-rmse:4.81702
[281]	validation_0-rmse:4.81832
[282]	validation_0-rmse:4.81962
[283]	validation_0-rmse:4.81835
[284]	validation_0-rmse:4.81804
[285]	validation_0-rmse:4.81823
[286]	validation_0-rmse:4.81833
[287]	validation_0-rmse:4.81888
[288]	validation_0-rmse:4.81850
[289]	validation_0-rmse:4.81758
[290]	validation_0-rmse:4.81793
[291]	validation_0-rmse:4.81868
[292]	validation_0-rmse:4.81932
[293]	validation_0-rmse:4.81995
[294]	validation_0-rmse:4.81969
[295]	validation_0-rmse:4.82014
[296]	validation_0-rmse:4.82075
[297]	validation_0-rmse:4.82050
[298]	validation_0-rmse:4.82113
[299]	validation_0-rmse:4.82150

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [27]:
y_pred = model.predict(X_test)

In [25]:
X_test

,sku_enc,category_enc,region_enc,weather_condition_enc,temperature,rainfall,humidity,month,day_of_week,is_weekend
7778,67,4,2,0,29.5,0.0,49.5,2,1,0
7779,82,2,2,1,10.4,8.1,74.0,2,1,0
7780,31,1,4,4,17.6,135.4,82.5,2,1,0
7781,46,0,0,1,22.5,0.0,53.0,2,1,0
7782,88,0,4,0,30.3,0.8,35.1,2,1,0
...,...,...,...,...,...,...,...,...,...,...
9151,49,0,0,1,25.2,13.1,60.6,10,2,0
9152,83,3,3,7,41.4,0.0,43.4,10,2,0
9153,74,6,4,6,19.5,64.0,72.2,10,3,0
9154,36,1,2,0,34.6,3.3,37.2,10,3,0
9155,0,3,4,4,12.4,133.5,77.1,10,3,0

In [28]:
# save this model
artifact = {
    "model": model,
    "encoders": encoders,
    "feature_cols": feature_cols,
}

with open("forecast_model.pkl", "wb") as f:
    pickle.dump(artifact, f)